# The official Kibana Docker image
FROM docker.elastic.co/kibana/kibana:8.4.3-amd64

# Copy our config file over
COPY --chown=1000:0 config/kibana.yml /usr/share/kibana/config/kibana.yml

# Allow Elasticsearch to create `elasticsearch.keystore`
RUN chmod g+ws /usr/share/kibana/config

USER 1000:0
