services:
- type: pserv
  name: Techpays Elasticsearch
  env: docker
  plan: starter plus
  disk:
    name: esdata
    mountPath: /usr/share/elasticsearch/data
    sizeGB: 10
  autoDeploy: false # so ES does not restart on a push to this repository.
  envVars:
  - key: ES_JAVA_OPTS
    value: "-Xms512m -Xmx512m"
  - key: discovery.type
    value: single-node
  - key: cluster.name
    value: elastic
